GET http://localhost:3001/api/persons/

###
GET http://localhost:3001/api/persons/641aa93a6c0d0c23fb31357b

###
DELETE  http://localhost:3001/api/persons/5 HTTP/1.1

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "Dan Abramov",
    "number": "12-34-567890"
}

###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "number": "12-34-567890"
}


###
POST http://localhost:3001/api/persons/ HTTP/1.1
content-type: application/json

{
    "name": "sample"
}